db:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=password

redis:
  image: redis:2.8.19

rabbitmq:
  image: tutum/rabbitmq
  environment:
    - RABBITMQ_PASS=password
  ports:
    - "5672:5672"
    - "15672:15672"

app:
  build: .
  command: ./run_web.sh
  volumes:
    - .:/app
  ports:
    - "8008:8000"
  links:
    - db:db
    - rabbitmq:rabbit
    - redis:redis

worker:
  build: .
  command: ./run_celery.sh
  volumes:
    - .:/app
  links:
    - db:db
    - rabbitmq:rabbit
    - redis:redis
