db:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=password

redis:
  image: redis:2.8.19

rabbitmq:
  image: tutum/rabbitmq
  environment:
    - RABBITMQ_PASS=password
  ports:
    - "5672:5672"
    - "15672:15672"

app:
  build: .
  command: sh ./run_app.sh
  volumes:
    - ./mydjangoapp:/app
  ports:
    - "8008:8000"
  links:
    - db:db
    - rabbitmq:rabbit
    - redis:redis

asyncapp:
  build: .
  command: sh ./run_async_app.sh
  volumes:
    - ./myaiohttpapp:/app
  ports:
    - "8009:8000"
  links:
    - db:db
    - rabbitmq:rabbit
    - redis:redis

worker:
  build: .
  command: sh ./run_celery_worker.sh
  volumes:
    - ./mydjangoapp:/app
  links:
    - db:db
    - rabbitmq:rabbit
    - redis:redis
